#!/usr/bin/env python3
"""
Verify no GPL-licensed packages are in the ARLD dependency graph.
Generates LICENSES.txt with SPDX identifiers for all known dependencies.
"""

import sys

BLOCKED_PREFIXES = ("GPL-", "AGPL-")

# SPDX identifiers for all direct and transitive dependencies.
# Update this table whenever a new dependency is added to vcpkg.json or CMakeLists.
DEPENDENCY_LICENSES: dict[str, str] = {
    # Runtime / build deps
    "Qt6 (LGPL dynamic link)":  "LGPL-3.0-only",
    "CGAL":                     "LGPL-3.0-or-later",
    "nlohmann-json":             "MIT",
    "Catch2":                    "BSL-1.0",
    # Transitive deps via vcpkg
    "boost":                     "BSL-1.0",
    "eigen3":                    "MPL-2.0",
    "gmp":                       "LGPL-3.0-or-later",
    "mpfr":                      "LGPL-3.0-or-later",
    "zlib":                      "Zlib",
    "libpng":                    "libpng",
    "libjpeg-turbo":             "IJG",
    # Phase 1 additions (listed now to keep manifest current)
    "libharu":                   "MIT",
    "stb":                       "MIT",
}


def main() -> int:
    violations: list[str] = []
    lines: list[str] = [
        "# ARLD Transitive Dependency License Inventory",
        "# Generated by scripts/check-licenses.py",
        "# No GPL-licensed code is permitted in distributable binaries.",
        "",
    ]

    for pkg, spdx in sorted(DEPENDENCY_LICENSES.items()):
        lines.append(f"{pkg}: {spdx}")
        if any(spdx.startswith(p) for p in BLOCKED_PREFIXES):
            violations.append(f"  BLOCKED  {pkg}: {spdx}")

    with open("LICENSES.txt", "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if violations:
        print("ERROR: GPL-licensed dependencies detected:")
        for v in violations:
            print(v)
        return 1

    print(f"License check passed — {len(DEPENDENCY_LICENSES)} packages verified.")
    print("LICENSES.txt written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
